import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Navbar } from '@/sections/Navbar'
import './globals.css'
import React from 'react'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          display: 'flex',
          height: '100vh',
          width: '100vw',
        }}
      >
        {' '}
        <NextIntlClientProvider>
          <aside>
            <Navbar />
          </aside>
          <main
            style={{
              flexGrow: 1,
              padding: '20px',
              display: 'flex',
              justifyContent: 'center',
              flexDirection: 'column',
              gap: '20px',
            }}
          >
            {children}
          </main>{' '}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
